version: "3.9"
services:
  go-jwt-authentication:
    image: sailor1921/go-jwt-authentication:v1.0.5
    restart: always
    environment:
      - MODE=production
      - MYSQL_PROVIDER_HOST=docker.for.mac.localhost
      - MYSQL_PROVIDER_PORT=3306
    ports:
      - 1004:8080
